2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_setup.py:_flush():69] setting env: {}
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_init.py:_log_setup():336] Logging user logs to /home/mansour/Music/OtherWork/Sauvalo/SauvolaNet/wandb/run-20210909_134536-30pfy4ly/logs/debug.log
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_init.py:_log_setup():337] Logging internal logs to /home/mansour/Music/OtherWork/Sauvalo/SauvolaNet/wandb/run-20210909_134536-30pfy4ly/logs/debug-internal.log
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_init.py:init():369] calling init triggers
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-09-09 13:45:36,879 INFO    MainThread:183722 [wandb_init.py:init():418] starting backend
2021-09-09 13:45:36,879 INFO    MainThread:183722 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-09 13:45:36,892 INFO    MainThread:183722 [backend.py:ensure_launched():123] starting backend process...
2021-09-09 13:45:36,898 INFO    MainThread:183722 [backend.py:ensure_launched():128] started backend process with pid: 183802
2021-09-09 13:45:36,899 INFO    MainThread:183722 [wandb_init.py:init():423] backend started and connected
2021-09-09 13:45:36,901 INFO    MainThread:183722 [wandb_init.py:init():465] updated telemetry
2021-09-09 13:45:36,901 INFO    MainThread:183722 [wandb_init.py:init():484] communicating current version
2021-09-09 13:45:37,594 INFO    MainThread:183722 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-09 13:45:37,594 INFO    MainThread:183722 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-09-09 13:45:37,955 INFO    MainThread:183722 [wandb_init.py:init():522] starting run threads in backend
2021-09-09 13:45:42,726 WARNING MainThread:183722 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 783, in communicate_run_start
    result = self._communicate(rec)
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/mansour/anaconda3/envs/v2/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
